USE ArtShop;

CREATE TABLE Stock
(
	ID UNIQUEIDENTIFIER DEFAULT NEWID()
	CONSTRAINT PK_Stock PRIMARY KEY,

	ID_Art UNIQUEIDENTIFIER NOT NULL
	CONSTRAINT FK_Art FOREIGN KEY 
	REFERENCES Art(ID)
	ON DELETE CASCADE 
	ON UPDATE CASCADE,

	ID_Warehouse UNIQUEIDENTIFIER NOT NULL
	CONSTRAINT FK_Warehouse FOREIGN KEY 
	REFERENCES Warehouse(ID)
	ON DELETE CASCADE 
	ON UPDATE CASCADE,
);