CREATE FUNCTION dbo.fArtID
(
	@SerialNumber VARCHAR(255)
)
RETURNS UNIQUEIDENTIFIER
AS
BEGIN
	DECLARE @ID_Art UNIQUEIDENTIFIER = 
			(SELECT TOP 1 ID
			FROM Art 
			WHERE SerialNumber = @SerialNumber)
	RETURN @ID_Art;
END;